// <auto-generated />
using System;
using ExpedientesAcademicos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpedientesAcademicos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502013807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpedientesAcademicos.Models.Alumno", b =>
                {
                    b.Property<int>("AlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumnoId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlumnoId");

                    b.ToTable("alumnos");
                });

            modelBuilder.Entity("ExpedientesAcademicos.Models.expediente", b =>
                {
                    b.Property<int>("expedienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("expedienteId"));

                    b.Property<decimal>("NotaFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("alumnoId")
                        .HasColumnType("int");

                    b.Property<int>("materiaId")
                        .HasColumnType("int");

                    b.HasKey("expedienteId");

                    b.HasIndex("alumnoId");

                    b.HasIndex("materiaId");

                    b.ToTable("expedientes");
                });

            modelBuilder.Entity("ExpedientesAcademicos.Models.materia", b =>
                {
                    b.Property<int>("materiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("materiaId"));

                    b.Property<string>("Docente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("materiaId");

                    b.ToTable("materias");
                });

            modelBuilder.Entity("ExpedientesAcademicos.Models.expediente", b =>
                {
                    b.HasOne("ExpedientesAcademicos.Models.Alumno", "Alumno")
                        .WithMany("Expedientes")
                        .HasForeignKey("alumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpedientesAcademicos.Models.materia", "materia")
                        .WithMany()
                        .HasForeignKey("materiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("materia");
                });

            modelBuilder.Entity("ExpedientesAcademicos.Models.Alumno", b =>
                {
                    b.Navigation("Expedientes");
                });
#pragma warning restore 612, 618
        }
    }
}
